# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 904524580cf80baab5a980d17c74ea322243822009f6e20afa172a2a8bb7c53215acdbe8c9a3d1ccafdaa38fee94d97a4383a3604ba0f07e01d9642bbd4f5e65

test:
  secret_key_base: 3d48eaaccef3c2e50f19dc1a3ab4136f360932e2005f2bcd4aa357bab0039bbfe4dae487b9dd99cf8a5e5d83a7dc24766be2414097f00d452cc3256548b95add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
